name: CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.12.4'
            
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: List installed packages
          run: pip list

        - name: Run tests
          run: python -m pytest

    build_model:
        runs-on: windows-latest
        needs: build

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.12.4'
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Build and train model
          run: python build_and_train_model.py
    
    deploy:
        runs-on: windows-latest
        needs: build_model

        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Deploy to server
          run: .\deploy.ps1
          env:
            DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}
